version: '3.8'

services:
  jaeger:
    image: jaegertracing/all-in-one:1.62.0
    environment:
      COLLECTOR_ZIPKIN_HOST_PORT: 9411
      COLLECTOR_OTLP_ENABLED: 'true'
    ports:
      - '6831:6831/udp' # Thrift UDP (agent)
      - '6832:6832/udp' # Thrift UDP (agent)
      - '5778:5778' # Configuration (agent)
      - '16686:16686' # Jaeger UI
      - '4317:4317' # OTLP gRPC
      - '4318:4318' # OTLP HTTP
      - '14250:14250' # Collector gRPC
      - '14268:14268' # Collector HTTP
      - '14269:14269' # Collector Admin
      - '9411:9411' # Zipkin
    restart: unless-stopped
    volumes:
      - jaeger-data:/tmp

  minio:
    image: quay.io/minio/minio:latest
    ports:
      - "9000:9000"
      - "9090:9090"
    entrypoint: >
      sh -c "
        minio server /data --console-address ':9090' &
        sleep 5 &&
        mc alias set local http://localhost:9000 minioadmin minioadmin &&
        mc mb --region=ru-central1 local/sitterly || true &&
        tail -f /dev/null
      "
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - ./data/minio_cache_1:/data1
      - ./data/minio_cache_2:/data2

  postgres_auth:
    image: postgres:15
    environment:
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_USER=myuser
      - POSTGRES_DB=postgres
    ports:
      - '5434:5432'
    volumes:
      - ./postgres_auth:/var/lib/postgresql/data

  postgres_order:
    image: postgres:15
    environment:
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_USER=myuser
      - POSTGRES_DB=postgres
    ports:
      - '5435:5432'
    volumes:
      - ./postgres_order:/var/lib/postgresql/data

  postgres_profile:
    image: postgres:15
    environment:
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_USER=myuser
      - POSTGRES_DB=postgres
    ports:
      - '5436:5432'
    volumes:
      - ./postgres_profile:/var/lib/postgresql/data

  postgres_rating:
    image: postgres:15
    environment:
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_USER=myuser
      - POSTGRES_DB=postgres
    ports:
      - '5437:5432'
    volumes:
      - ./postgres_rating:/var/lib/postgresql/data

  #  nest_auth:
  #    build:
  #      context: ./auth-user-app
  #      dockerfile: Dockerfile
  #      args:
  #        - NODE_ENV=development
  #    dns:
  #      - 8.8.8.8
  #    ports:
  #      - 1010:3000
  #      - 51055:50055
  #    environment:
  #      - NODE_ENV=development
  #      - PORT=3000
  #      - PG_USERNAME=myuser
  #      - PG_PASSWORD=mypassword
  #      - PG_DATABASE=postgres
  #      - PG_HOST=postgres_auth
  #      - PG_PORT=5432
  #      - REDIS_URL=redis://redis:6379
  #      - MINIO_URL=http://minio:9000
  #      - RPC_HOST=nest_auth:50055
  #      - SWAGGER_TITLE=AuthUser App
  #      - SERVICE_NAME=AuthUser App
  #      - SWAGGER_DESC=Сервис AuthUser
  #    volumes:
  #      - .:/usr/src/app
  #    depends_on:
  #      - mongodb
  #      - redis
  #      - postgres_auth
  #      - jaeger

  nest_order:
    build:
      context: ./order-app
      dockerfile: Dockerfile
      args:
        - NODE_ENV=development
    dns:
      - 8.8.8.8
    ports:
      - 2020:3000
      - 52055:50055
    environment:
      - PORT=3000
      - PG_USERNAME=myuser
      - PG_PASSWORD=mypassword
      - PG_DATABASE=postgres
      - PG_HOST=postgres_order
      - PG_PORT=5432
      - REDIS_URL=redis://redis:6379
      - RPC_HOST=nest_order:50055
      - SWAGGER_TITLE=Order App
      - SERVICE_NAME=Order App
      - SWAGGER_DESC=Сервис Order
    volumes:
      - .:/usr/src/app
    depends_on:
      - mongodb
      - redis
      - postgres_order
      - jaeger

  nest_profile:
    build:
      context: ./profile-app
      dockerfile: Dockerfile
      args:
        - NODE_ENV=development
    dns:
      - 8.8.8.8
    ports:
      - 3030:3000
      - 53055:50055
    environment:
      - PORT=3000
      - PG_USERNAME=myuser
      - PG_PASSWORD=mypassword
      - PG_DATABASE=postgres
      - PG_HOST=postgres_profile
      - PG_PORT=5432
      - REDIS_URL=redis://redis:6379
      - RPC_HOST=nest_profile:50055
      - SWAGGER_TITLE=Profile App
      - SERVICE_NAME=Profile App
      - SWAGGER_DESC=Сервис Profile
    volumes:
      - .:/usr/src/app
    depends_on:
      - mongodb
      - redis
      - postgres_profile
      - jaeger

  nest_rating:
    build:
      context: ./rating-app
      dockerfile: Dockerfile
      args:
        - NODE_ENV=development
    dns:
      - 8.8.8.8
    ports:
      - 4040:3000
      - 54055:50055
    environment:
      - PORT=3000
      - PG_USERNAME=myuser
      - PG_PASSWORD=mypassword
      - PG_DATABASE=postgres
      - PG_HOST=postgres_rating
      - PG_PORT=5432
      - REDIS_URL=redis://redis:6379
      - RPC_HOST=nest_rating:50055
      - SWAGGER_TITLE=Rating App
      - SERVICE_NAME=Rating App
      - SWAGGER_DESC=Сервис Rating
    volumes:
      - .:/usr/src/app
    depends_on:
      - mongodb
      - redis
      - postgres_rating
      - jaeger

  redis:
    image: 'redis:alpine'
    ports:
      - '6379:6379'

  mongodb:
    image: 'mongo:latest'
    ports:
      - '27017:27017'
    volumes:
      - ./data:/data/db
    environment:
      - MONGODB_DATABASE=db
    restart: unless-stopped

volumes:
  jaeger-data:
  postgres_data:
